using System.Reflection;

namespace Zonit.Extensions.Databases.Accessors;

/// <summary>
/// Non-generic interface for AOT-safe property access on entities.
/// </summary>
public interface IEntityAccessor
{
    /// <summary>
    /// Gets the PropertyInfo for the specified property name.
    /// Uses cached PropertyInfo to avoid repeated reflection calls.
    /// </summary>
    /// <param name="propertyName">Name of the property.</param>
    /// <returns>PropertyInfo or null if not found.</returns>
    PropertyInfo? GetPropertyInfo(string propertyName);

    /// <summary>
    /// Gets the value of a property on the entity without reflection.
    /// </summary>
    /// <param name="entity">The entity instance.</param>
    /// <param name="propertyName">Name of the property.</param>
    /// <returns>Property value or null.</returns>
    object? GetValue(object entity, string propertyName);

    /// <summary>
    /// Sets the value of a property on the entity without reflection.
    /// </summary>
    /// <param name="entity">The entity instance.</param>
    /// <param name="propertyName">Name of the property.</param>
    /// <param name="value">Value to set.</param>
    /// <returns>True if property was found and set; false otherwise.</returns>
    bool SetValue(object entity, string propertyName, object? value);
}

/// <summary>
/// Generic interface for AOT-safe property access on entities.
/// Generated by EntityAccessorGenerator for each [DatabaseEntity] class.
/// </summary>
/// <typeparam name="TEntity">The entity type.</typeparam>
public interface IEntityAccessor<TEntity> : IEntityAccessor where TEntity : class
{
    /// <summary>
    /// Gets the value of a property on the entity without reflection.
    /// </summary>
    /// <param name="entity">The entity instance.</param>
    /// <param name="propertyName">Name of the property.</param>
    /// <returns>Property value or null.</returns>
    object? GetValue(TEntity entity, string propertyName);

    /// <summary>
    /// Sets the value of a property on the entity without reflection.
    /// </summary>
    /// <param name="entity">The entity instance.</param>
    /// <param name="propertyName">Name of the property.</param>
    /// <param name="value">Value to set.</param>
    /// <returns>True if property was found and set; false otherwise.</returns>
    bool SetValue(TEntity entity, string propertyName, object? value);
}
