name: Publish NuGet Packages

on:
  push:
    branches:
      - main
    paths:
      - 'Source/**/*.csproj'
      - 'Source/**/*.cs'
      - 'Source/Directory.Packages.props' 
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Możesz zmienić na windows-latest, jeśli wolisz

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK (8.0)
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Ustawienie .NET 8.0 SDK

    - name: Restore dependencies for .NET 8.0
      run: dotnet restore

    - name: Build and Publish for .NET 8.0
      run: |
        dotnet build --configuration Release --framework net8.0
        dotnet publish --configuration Release --framework net8.0 --output ./publish/net8.0
        dotnet pack --configuration Release --framework net8.0 --output ./nupkgs

    - name: Set up .NET SDK (9.0)
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'  # Ustawienie .NET 9.0 SDK

    - name: Restore dependencies for .NET 9.0
      run: dotnet restore

    - name: Build and Publish for .NET 9.0
      run: |
        dotnet build --configuration Release --framework net9.0
        dotnet publish --configuration Release --framework net9.0 --output ./publish/net9.0
        dotnet pack --configuration Release --framework net9.0 --output ./nupkgs

    - name: Publish NuGet packages
      run: |
        dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json