name: Publish NuGet Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Source/**/*.csproj'
      - 'Source/**/*.cs'
      - 'Source/Directory.Packages.props' 
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8 and 9 SDKs
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build, publish, and pack (.NET 8)
      run: |
        dotnet build --configuration Release --framework net8.0
        dotnet publish --configuration Release --framework net8.0 --output ./publish/net8.0
        dotnet pack --configuration Release --framework net8.0 --output ./nupkgs

    - name: Build, publish, and pack (.NET 9)
      run: |
        dotnet build --configuration Release --framework net9.0
        dotnet publish --configuration Release --framework net9.0 --output ./publish/net9.0
        dotnet pack --configuration Release --framework net9.0 --output ./nupkgs

    - name: Publish NuGet packages
      run: |
        dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json