name: Publish NuGet Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Source/**/*.csproj'
      - 'Source/**/*.cs'
      - 'Source/Directory.Packages.props' 
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8 and 9 SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore Source/**/*.csproj

      - name: Build all projects
        run: dotnet build Source/**/*.csproj --configuration Release --no-restore

      - name: Publish all projects (net8.0)
        run: |
          for proj in $(find Source -name '*.csproj'); do
            dotnet publish "$proj" --configuration Release --framework net8.0 --output ./publish/$(basename "$proj" .csproj)-net8.0
          done

      - name: Publish all projects (net9.0)
        run: |
          for proj in $(find Source -name '*.csproj'); do
            dotnet publish "$proj" --configuration Release --framework net9.0 --output ./publish/$(basename "$proj" .csproj)-net9.0
          done

      - name: Pack all libraries (multi-target .nupkg)
        run: |
          for proj in $(find Source -name '*.csproj'); do
            dotnet pack "$proj" --configuration Release --output ./nupkgs
          done

      - name: Publish NuGet packages
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json